routes/web.php
<?php

use \App\Http\Controllers\HomeController;
use \App\Http\Controllers\AdminController;
use \App\Http\Controllers\ChallengeController;
use \App\Http\Controllers\LeaderboardController;
use \App\Http\Controllers\UserController;

/*
  |--------------------------------------------------------------------------
  | Web Routes
  |--------------------------------------------------------------------------
  |
  | Here is where you can register web routes for your application. These
  | routes are loaded by the RouteServiceProvider within a group which
  | contains the "web" middleware group. Now create something great!
  |
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('/home', [HomeController::class, 'index'])->name('home');

Route::get('/admin', [AdminController::class, 'index'])->name('admin');

Route::resource('challenges', 'ChallengeController',
                [
                    'except' => ['index', 'create', 'destroy'],
                ]);
Route::post('/challenges/{challenge}/verify', [ChallengeController::class, 'verify'])
    ->name('challenges.verify');

Route::post('/users/{user}/pay', [UserController::class, 'pay'])->name('users.pay');
Route::get('/users/{user}', [UserController::class, 'show'])->name('users.show');
Route::delete('/users/{user}', [UserController::class, 'destroy'])->name('users.destroy');

Route::get('/leaderboard', [LeaderboardController::class, 'index'])->name('leaderboard');

Auth::routes();

resources/views/admin.blade.php
@extends('layouts.app')

@section('title', '- Admin')

@section('content')
    <div class="container">
        @if (session('status'))
            <div class="row justify-content-center">
                <div class="col-md-8">
                    <div class="card">
                        <div class="card-header">Admin</div>
                        <div class="card-body">
                            <div class="alert alert-success" role="alert">
                                {{ session('status') }}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        @endif

        <h1>Admin</h1>

        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header">
                        <h5>
                            <a class="d-block" href="#nwuitdaging" data-toggle="collapse">Nieuwe uitdaging</a>
                        </h5>
                    </div>
                    <div class="card-body collapse" id="nwuitdaging">
                        @if($errors->any())
                            <div class="alert alert-warning">
                                <ul>
                                    @foreach ($errors->all() as $error)
                                        <li>{{ $error }}</li>
                                    @endforeach
                                </ul>
                            </div>
                        @endif

                        <form action="{{ route('challenges.store') }}" method="post">
                            @csrf
                            <div class="form-group">
                                <label for="title">Titel</label>
                                <input name="title" id="title" type="text" value="{{ old('title') }}" class="form-control" />
                            </div>
                            <div class="form-group">
                                <label for="description">Beschrijving</label>
                                <textarea class="form-control" id="description" name="description" type="text" value="{{ old('description') }}"></textarea>
                            </div>
                            <div class="form-group">
                                <label for="answer">Antwoord</label>
                                <input id="answer" class="form-control" name="answer" type="text" value="{{ old('answer') }}"/>
                            </div>
                            <div class="form-group">
                                <label for="reward">Geldbeloning</label>
                                <input id="reward" class="form-control" name="reward" type="number" value="{{ old('reward') }}"/>
                            </div>
                            <div class="form-group">
                                <div class="label" for="score_reward">
                                    Beloning
                                </div>
                                <input class="form-control" id="score_reward" name="score_reward" type="number" value="{{ old('score_reward') }}"/>
                            </div>
                            <div class="form-group">
                                <label for="solve_limit">Limiet (0 voor geen limiet)</label>
                                <input id="solve_limit" class="form-control" name="solve_limit" type="number" min="0" value="{{ old('solve_limit', 0) }}" />
                            </div>
                            <div class="form-group form-check">
                                <input id="open" class="form-check-input" name="open" type="checkbox" value="1" />
                                <label for="open">Open</label>
                            </div>
                            <button type="submit" class="btn btn-primary">Opslaan</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>

        <h2>Teams</h2>
        @foreach ($users as $user)
            <div class="row justify-content-center mb-3">
                <div class="col-md-8">
                    <div class="card">
                        <div class="card-header">
                            <h5>
                                <a class="d-block" href="#user{{ $user->id }}" data-toggle="collapse">{{ $user->name }}</a>
                            </h5>
                        </div>
                        <div class="card-body collapse" id="user{{ $user->id }}">
                            <p class="card-text">
                                <a href="{{ route('users.show', ['user' => $user]) }}">{{ $user->name }}</a>
                            </p>
                            <hr/>
                            <p class="card-text">
                                Bankrekening: €{{ $user->money }}
                            </p>
                            <p class="card-text">
                                {{ $user->solves()->count() }} challenge(s) opgelost.
                            </p>
                            <hr/>
                            <form action="{{ route('users.pay', ['user' => $user]) }}" method="post">
                                @csrf
                                <div class="form-group">
                                    <label for="amount">Te betalen</label>
                                    <input class="form-control" name="amount" type="number" value="{{ old('amount') }}"/>
                                </div>
                                <button type="submit" class="btn btn-primary">Betalen</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        @endforeach

        <h2>Challenges</h2>
        @foreach ($challenges as $challenge)
            @component('components.adminchallenge', ['challenge' => $challenge])
            @endcomponent
        @endforeach
    </div>
@endsection

resources/views/challenge.blade.php
@extends('layouts.app')

@section('title', '- ' . $challenge->title)

@section('content')
    <div class="container">
        <h1>
            {{ $challenge->title }}
            @if ($challenge->solve_limit != 0)
                <span class="float-right badge badge-info mx-1">
                    Limiet: {{ $challenge->solve_limit }}
                </span>
            @else
                <span class="float-right badge badge-success mx-1">
                    Opgelost: {{ $challenge->solves->count() }}
                </span>
            @endif
            @if ($challenge->open)
                <span class="float-right badge badge-primary mx-1">
                    Open
                </span>
            @endif
        </h1>

        <p>
            @markdown($challenge->description)
        </p>

        <hr/>
        <h2>Eigenschappen</h2>
        @can('admin')
            <p class="card-text">
                <strong>Antwoord: </strong>{{ $challenge->answer }}
            </p>
        @endcan
        <p class="card-text">
            <strong>Geldbeloning: </strong>€{{ $challenge->reward }}
        </p>
        <p class="card-text">
            <strong>Beloning: </strong>{{ $challenge->score_reward }} punten
        </p>
        <p class="card-text">
            <strong>Straf voor fout: </strong>€{{ $challenge->penalty }}
        </p>

        <hr/>
        <h2>Opgelost door</h2>
        <ul>
            @foreach ($challenge->solves as $solve)
                <li><a href="{{ route('users.show', ['user' => $solve->user]) }}">{{ $solve->user->name }}</a></li>
            @endforeach
        </ul>

    </div>
@endsection

resources/views/edit.blade.php
@extends('layouts.app')

@section('title', '- Bewerk ' . $challenge->title)

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                @if($errors->any())
                    <div class="alert alert-warning">
                        <ul>
                            @foreach ($errors->all() as $error)
                                <li>{{ $error }}</li>
                            @endforeach
                        </ul>
                    </div>
                @endif
            </div>
        </div>
        <div class="row justify-content-center">
            <div class="col-md-8">
                <form action="{{ route('challenges.update', ['challenge' => $challenge]) }}" method="post">
                    @method('PATCH')
                    @csrf
                    <div class="form-group">
                        <label for="title">Titel</label>
                        <input name="title" id="title" type="text" value="{{ old('title', $challenge->title) }}" class="form-control" />
                    </div>
                    <div class="form-group">
                        <label for="description">Beschrijving</label>
                        <textarea class="form-control" id="description" name="description" type="text">{{ old('description', $challenge->description) }}</textarea>
                    </div>
                    <div class="form-group">
                        <label for="answer">Antwoord</label>
                        <input id="answer" class="form-control" name="answer" type="text" value="{{ old('answer', $challenge->answer) }}"/>
                    </div>
                    <div class="form-group">
                        <label for="reward">Geldbeloning</label>
                        <input id="reward" class="form-control" name="reward" type="number" value="{{ old('reward', $challenge->reward) }}"/>
                    </div>
                    <div class="form-group">
                        <div class="label" for="score_reward">
                            Beloning
                        </div>
                        <input class="form-control" id="score_reward" name="score_reward" type="number" value="{{ old('score_reward', $challenge->score_reward) }}"/>
                    </div>
                    <div class="form-group">
                        <label for="solve_limit">Limiet (0 voor geen limiet)</label>
                        <input id="solve_limit" class="form-control" name="solve_limit" type="number" min="0" value="{{ old('solve_limit', $challenge->solve_limit) }}" />
                    </div>
                    <div class="form-group form-check">
                        <input name="open" type="hidden" value="0"/>
                        <input id="open" class="form-check-input" name="open" type="checkbox" value="1" @if(old('open', $challenge->open)) checked @endif />
                        <label for="open">Open</label>
                    </div>
                    <button type="submit" class="btn btn-primary">Opslaan</button>
                </form>
            </div>
        </div>
    </div>
@endsection

resources/views/home.blade.php
@extends('layouts.app')
@section('title', '- Home')

@section('content')
    <div class="container">
        @if (isset($solved))
            <div class="row">
                <div class="col">
                    <div class="alert alert-success">
                        Je hebt de opdracht <span class="font-italic">{{ $solved }}</span> correct opgelost!
                    </div>
                </div>
            </div>
        @endif

        @if (isset($wrong))
            <div class="row">
                <div class="col">
                    <div class="alert alert-danger">
                        Je antwoord op de opdracht <span class="font-italic">{{ $wrong }}</span> was fout.
                        Je bent nu geld kwijt.
                    </div>
                </div>
            </div>
        @endif

        @if (isset($late))
            <div class="row">
                <div class="col">
                    <div class="alert alert-secondary">
                        Iemand anders heeft de opdracht <i>{{ $late }}</i> al opgelost.
                    </div>
                </div>
            </div>
        @endif

        <!-- Wrapper for toasts -->
        <div id="toastapp">
            <div class="alert alert-warning" v-for="solve in solves" role="alert">
                <h4 class="alert-heading">
                    Uitdaging opgelost
                </h4>
                <p>
                    De uitdaging <i>@{{ solve.challenge.title }}</i> is opgelost door team <i>@{{ solve.user.name }}</i>.
                </p>
            </div>
        </div>

        @if (session('status'))
            <div class="row justify-content-center">
                <div class="col-md-8">
                    <div class="card">
                        <h5 class="card-header">Dashboard</h5>
                        <div class="card-body">
                            <div class="alert alert-success" role="alert">
                                {{ session('status') }}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        @endif

        <div class="row justify-content-center mb-3">
            <div class="col-md-8">
                <div class="card">
                    <h5 class="card-header">
                        {{ Auth::user()->name }}
                    </h5>
                    <div class="card-body">
                        <p class="card-text">
                            €{{ Auth::user()->money }}
                        </p>
                        <p class="card-text">
                            {{ Auth::user()->score }} punten
                        </p>
                    </div>
                </div>
            </div>
        </div>

        <h1>Challenges</h1>

        @if ($challenges->count() === 0)
            <div class="alert alert-primary">
                Geen uitdagingen beschikbaar.
            </div>
        @endif

        @if($errors->any())
            <div class="alert alert-warning">
                <ul>
                    @foreach ($errors->all() as $error)
                        <li>{{ $error }}</li>
                    @endforeach
                </ul>
            </div>
        @endif
        @foreach ($challenges as $challenge)
            @component('components.submitchallenge', ['challenge' => $challenge])
            @endcomponent
        @endforeach
    </div>
@endsection

@section('js')
    <script>
        var app = new Vue({
            el: '#toastapp',
            data: {
                solves: [],
                prev: {{ $prev }}
            },
            methods: {
                loadData: function() {
                    fetch('{{ route('solves') }}?start=' + this.prev)
                        .then(res => res.json())
                        .then(function(out) {
                            this.solves = out;
                            var i = out.length - 1;
                            if (i >= 0)
                                this.prev = out[i].id;
                        }.bind(this));
                },
            },
            mounted: function() {
                this.loadData();

                setInterval(function() {
                    this.loadData();
                }.bind(this), 10000);
            }
        });
    </script>
@endsection

resources/views/leaderboard.blade.php
@extends('layouts.app')

@section('title', '- Leaderboard')

@section('extrascript')
    <script src="{{ asset('js/chart.min.js') }}"></script>
@endsection

@section('content')
    <style>
        @media (min-width: 992px)
        {
            #leaderboardcontainer {
                min-width: 90%;
                width: 90%;
            }
        }
    </style>
    </style>
    <div id="leaderboardcontainer" class="container">
        <div class="row">
            <div class="col">
                <canvas id="scoreCanvas"></canvas>
            </div>
        </div>
        <div class="row">
            <div class="col">
                <div class="table-responsive" id="vue-table">
                    <table class="table table-dark table-striped">
                        <thead>
                            <tr>
                                <th scope="col">#</th>
                                <th scope="col">Naam</th>
                                <th scope="col">Score</th>
                                <th scope="col">Geld</th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr v-for="(team, index) in teams" :key="index">
                                <th scope="row">@{{ index+1 }}</th>
                                <td><a v-bind:href="teamUrl + '/' + team.id" class="text-light">@{{ team.name }}</a></td>
                                <td>@{{ team.score }} punten</td>
                                <td>€ @{{ team.money }}</td>
                            </tr>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
@endsection

@section('js')
    <script>
        var barChartData = {
            labels: ['Laden'],
            datasets: [{
                label: 'Score',
                backgroundColor: "rgba(100, 0, 0, 0.5)",
                yAxisID: 'solves-y-axis',
                data: [1]
            }, {
                label: 'Geld',
                backgroundColor: "rgba(0, 0, 100, 0.5)",
                yAxisID: 'money-y-axis',
                data: [1]
            }]
        };

        var app = new Vue({
            el: '#vue-table',
            data: {
                teams: [
                    {
                        name: "Laden",
                        solves: [1, 2],
                        money: 10,
                    }
                ],
                teamUrl: "{{ route('users.show', ['user' => '']) }}"
            }
        });


        function updateData() {
            fetch("{{ route('leaderboard.data') }}")
                .then(res => res.json())
                .then((out) => {
                    app.teams = out;
                    barChartData.labels = out.map(x => x.name);
                    barChartData.datasets[0].data = out.map(x => x.score);
                    barChartData.datasets[1].data = out.map(x => x.money);
                    window.myBar.update();
                });
        }

        window.onload = function() {
			var ctx = document.getElementById('scoreCanvas').getContext('2d');
			window.myBar = new Chart(ctx, {
				type: 'bar',
				data: barChartData,
				options: {
					responsive: true,
					legend: {
						position: 'top',
					},
					title: {
						display: true,
						text: 'Leaderboard'
					},
                    scales: {
                        yAxes: [{
                            id: 'solves-y-axis',
                            type: 'linear',
                            position: 'left',
                            ticks: {
                                beginAtZero: true,
                                min: 0,
                            },
                        },{
                            id: 'money-y-axis',
                            type: 'linear',
                            position: 'right',
                            ticks: {
                                beginAtZero: true,
                                min: 0,
                            },
                        }]
                    }
				}
			});
            updateData();
            window.setInterval(updateData, 5000);
		};
    </script>
@endsection

resources/views/user.blade.php
@extends('layouts.app')

@section('title', '- '.$user->name)

@section('content')
    <div class="container">
        <h1>
            {{ $user->name }}
            @if ($user->is_admin)
                <span class="float-right badge badge-danger mx-1">
                    Admin
                </span>
            @endif
        </h1>

        <hr/>
        <form action="{{ route('users.destroy', $user) }}" method="post">
            @csrf
            @method('DELETE')
            <button type="submit">Delete User</button>
        </form>
        <a class="btn btn-danger" href="{{ route("delete-user", $user) }}">Delete user</a>
        <hr />
        <h2>Eigenschappen</h2>
        <p class="card-text">
            <strong>Email: </strong>{{ $user->email }}
        </p>
        <p class="card-text">
            <strong>Geld: </strong>€{{ $user->money }}
        </p>
        <p class="card-text">
            <strong>Score: </strong>{{ $user->score }} punten
        </p>

        <hr/>
        <h2>Opgeloste uitdagingen</h2>
        <ul>
            @foreach ($user->solves as $solve)
                <li><a href="{{ route('challenges.show', ['challenge' => $solve->challenge]) }}">{{ $solve->challenge->title }}</a></li>
            @endforeach
        </ul>

    </div>
@endsection